sudo: false
language: node_js
node_js:
  - 12

cache:
  bundle: true
  directories:
    - node_modules

jobs:
  include:
    - stage: Document deploy
      allow_failure: true
      script: npx lerna run build && npm run example:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: dist

    - stage: Unit testing
      before_script: npx lerna run build && npm install codecov --no-save
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
